jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: EXCLUSIVE # set to NORMAL to allow running jobs on the master

  globalNodeProperties:
    - envVars:
        env:
          - key: FOO
            value: BAR

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  agentProtocols:
  - "JNLP4-connect"
  - "Ping"

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false

  disableRememberMe: false
  markupFormatter: "plainText"
  myViewsTabBar: "standard"
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        password: "admin"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"


security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  sSHD:
    port: -1
# the following is for jenkins <2.165
##  remotingCLI:
##    enabled: false


##credentials:
##  system:
##    domainCredentials:
##      - credentials:
##          - string:
##              scope: GLOBAL
##              id: slack-token
##              secret: "${SLACK_TOKEN}"
##              description: Slack token


unclassified:
  buildStepOperation:
    enabled: false
  defaultFolderConfiguration:
    healthMetrics:
    - worstChildHealthMetric:
        recursive: true
  gitHubPluginConfig:
    hookUrl: "http://localhost:8080/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  timestamperConfig:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  upstream:
    globalUpstreamFilterStrategy: UseOldest
  whitelist:
    enabled: false
##  artifactorybuilder:
##    useCredentialsPlugin: true
##    artifactoryServers:
##      - serverId: artifactory
##        artifactoryUrl: http://acme.com/artifactory
##        resolverCredentialsConfig:
##          username: artifactory_user
##          password: ${ARTIFACTORY_PASSWORD}
##  slackNotifier:
#     teamDomain: <your-slack-workspace-name> # i.e. your-company (just the workspace name not the full url)
#       tokenCredentialId: slack-token
#

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
